### PR TITLE
Remove Jenkins volume from state module

### PR DESCRIPTION
**Pull request by dippynark**
**What this PR does / why we need it**: A Jenkins volume is created by the state module that isn't actually used by Jenkins (as the Jenkins module creates one). This fixes that.

```release-note
Remove unnecessary Jenkins volume from state module
```

### CODE REVIEW

**Comment by dippynark** [comment]
@MattiasGees I've removed that already?

**Comment by MattiasGees** [comment]
correct, for some reason I looked over it
/lgtm

**Pull request merged**
