### PR TITLE
Enables wing-dev-mode on bastion instances

### PR DESCRIPTION
**Pull request by JoshVanL**
```release-note
Enable `--wing-dev-mode` on bastion instances for Wing development
```

/assign

### CODE REVIEW

**Comment by simonswine** [comment]
I am having some issues destroying the thing again:

```
DEBU[0380] 2 errors occurred:                            app=tarmak module=terraform std=err
DEBU[0380]      * module.kubernetes.aws_iam_policy_attachment.wing_binary_read (destroy): 1 error occurred:  app=tarmak module=terraform std=err
DEBU[0380]      * aws_iam_policy_attachment.wing_binary_read: [WARN] Error removing user, role, or group list from IAM Policy Detach csire-cluster-wing-binary:  app=tarmak module=terraform std=err
DEBU[0380] – NoSuchEntity: Policy arn:aws:iam::228615251467:policy/bastion.csire-cluster.wing_binary_read was not found.  app=tarmak module=terraform std=err
DEBU[0380]      status code: 404, request id: 627c1585-158a-11e9-8bb1-939f55c828e0  app=tarmak module=terraform std=err
DEBU[0380]                                               app=tarmak module=terraform std=err
DEBU[0380]                                               app=tarmak module=terraform std=err
DEBU[0380]      * module.vault.aws_iam_policy_attachment.wing_binary_read (destroy): 1 error occurred:  app=tarmak module=terraform std=err
DEBU[0380]      * aws_iam_policy_attachment.wing_binary_read: [WARN] Error removing user, role, or group list from IAM Policy Detach csire-cluster-wing-binary:  app=tarmak module=terraform std=err
DEBU[0380] – NoSuchEntity: Policy arn:aws:iam::228615251467:policy/bastion.csire-cluster.wing_binary_read was not found.  app=tarmak module=terraform std=err
DEBU[0380]      status code: 404, request id: 5dbfedb0-158a-11e9-9c43-115e0575bb14  app=tarmak module=terraform std=err
```

Are you able to reproduce it?

/assign @JoshVanL 
/unassign

**Comment by JoshVanL** [comment]
@simonswine 
Yeah sorry about that I am. Have a fix so will add shortly.
This is an issue with using multiple attachments on the same policy across roles. 
Using `iam_role_policy_attachment` instead fixes the issue

**Comment by JoshVanL** [comment]
https://github.com/hashicorp/terraform/issues/5979

**Comment by simonswine** [comment]
```
Jan 11 13:51:01 ip-10-99-32-10.eu-west-1.compute.internal sh[5416]: fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
Jan 11 13:50:25 bastion.develop.tarmak.org sh[5104]: fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```

Both bastion and vault-1 fail

/assign @JoshVanL 
/unassign

**Comment by simonswine** [comment]
Thank you very much @JoshVanL, seems to work prefect now
/approve
/lgtm

**Pull request merged**
