### PR TITLE
Upgrade fluentbit to 1.0.4

### PR DESCRIPTION
**Pull request by simonswine**
Signed-off-by: Christian Simon <simon@swine.de>

```release-note
Upgrade fluentbit to 1.0.4
```

### CODE REVIEW

**Comment by simonswine** [comment]
Over to you

/assign @JoshVanL

**Comment by JoshVanL** [comment]
fluent-bit pods failing for me

```Warning  Failed   2m31s (x5 over 3m58s)  kubelet, ip-10-99-48-239.eu-west-1.compute.internal  Error: failed to start container "fluent-bit": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"```

**Comment by simonswine** [comment]
Thanks good catch, was not straightforward to fix they removed busybox from their image

/assign @JoshVanL 
/unassign

**Pull request merged**
