### PR TITLE
Bump fluent bit daemonset to latest version

### LINKED ISSUE #583: Fluentbit 0.13.1 crashes frequently
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
fluentbit version used by tarmak crashes frequently:

```
Fluent-Bit v0.13.1
Copyright (C) Treasure Data

#0 0x7fb614850e2f in ???() at ???:0
#1 0x558c51945ae2 in msgpack_sbuffer_write() at lib/msgpack-2.1.3/include/msgpack/sbuffer.h:84
#2 0x558c51b57155 in msgpack_pack_ext_body() at lib/msgpack-2.1.3/include/msgpack/pack_template.h:890
#3 0x558c51b57155 in msgpack_pack_object() at lib/msgpack-2.1.3/src/objectc.c:72
#4 0x558c519464c4 in pack_map_content() at plugins/filter_kubernetes/kubernetes.c:321
#5 0x558c51946d12 in cb_kube_filter() at plugins/filter_kubernetes/kubernetes.c:491
#6 0x558c518e69aa in flb_filter_do() at src/flb_filter.c:86
#7 0x558c518e43fc in flb_input_dbuf_write_end() at include/fluent-bit/flb_input.h:642
#8 0x558c518e5f5c in flb_input_dyntag_append_raw() at src/flb_input.c:894
#9 0x558c5190a98d in process_content() at plugins/in_tail/tail_file.c:290
#10 0x558c5190b7d8 in flb_tail_file_chunk() at plugins/in_tail/tail_file.c:651
#11 0x558c519091c7 in in_tail_collect_static() at plugins/in_tail/tail.c:129
#12 0x558c518e649b in flb_input_collector_fd() at src/flb_input.c:995
#13 0x558c518ed1de in flb_engine_handle_event() at src/flb_engine.c:296
#14 0x558c518ed1de in flb_engine_start() at src/flb_engine.c:515
#15 0x558c5188d4c6 in main() at src/fluent-bit.c:824
#16 0x7fb6147482e0 in ???() at ???:0
#17 0x558c5188b949 in ???() at ???:0
#18 0xffffffffffffffff in ???() at ???:0
```

people are seeing this one a lot on fluent/fluent-bit:0.13.1 (what we are running)
https://github.com/fluent/fluent-bit/issues/584

**What you expected to happen**:

Fluentbit keeps on running

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by MattiasGees**
**What this PR does / why we need it**:
Bump fluentbit to the latest version and brings it in sync with the host fluentbit.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #583 

**Special notes for your reviewer**:
Tested and logs are shipping without errors.

**Release note**:

```release-note
Bump fluentbit to 0.14.6
```

### CODE REVIEW

**Comment by simonswine** [comment]
Can we investigate if we can lock the version of the rpm installed package?

/unassign
/assign @MattiasGees @JoshVanL

**Comment by MattiasGees** [comment]
@simonswine in the yum repo index, they only advertise the latest version. I see two solution if we want to pin it to a specific version.

1. Download the specific version we want from fluent-bit. The earlier versions are still available, but they are not indexed anymore. Once we downloaded it, we can install it.
2. Host our own yum repo and serve the version from there. This would mean we have to manage a repo.

If we want to pin it, I would go for option 1.

**Comment by simonswine** [comment]
I am not too sure how the verification for (1.) would work?

Maybe a 2b:
If we mirror the index and the latest package right now we should be able to keep reusing their GPG keys?  That could be just done on our releases.tarmak.io bucket. Updates to that package version would be quite manual though. Wdyt?

**Comment by MattiasGees** [comment]
@simonswine this would also mean that we will have to create a separate clone/index/repo every time we bump fluent-bit in Tarmak with solution 2b.

**Comment by simonswine** [comment]
I have implemented now 2b and some automation to clone the repo

**Comment by simonswine** [comment]
Ideally problems should be caught by fluent-bit accentance tests (like updating without creating the repo)

**Pull request merged**
