### PR TITLE
Packer image updates

### LINKED ISSUE #557: kdump.service & network.service failing
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
(perhaps?)

**What happened**:
I recently created a new Tarmak cluster in response to support ticket. The customer referenced the failing kdump and network services.

These were unrelated to the issue but they had caused confusion.

On my nodes the kdump and network were failing as follows:

| node    | kdump   | network |
|---------|---------|---------|
| master  |         | failing |
| vault   | failing | failing |
| worker  |         | failing |
| etcd    |         | failing |
| bastion | failing | failing |

**What you expected to happen**:
When a node is healthy, for it to have no failing systemd units so as not to distract from other issues.

**How to reproduce it (as minimally and precisely as possible)**:
I have seen this on other, if not most clusters I've worked on before but have never looked into the cause.

### PR DESCRIPTION
**Pull request by simonswine**
Fixes #557 

```release-note
Fix failing services (network.service, kdump.service) [requires packer build] 
Removes generated host keys as last step (depending on available upgrades, host key are regenerated after)[requires packer build]
Switch back to upstream aws cli package
```

### CODE REVIEW

**Comment by simonswine** [comment]
If you could give this a run (packer build + building a single cluster). Check the status of the nodes by sshing into them and make sure no systemd job is in failed status

/unassign
/assign @alljames

**Comment by alljames** [comment]
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster instance list
```
ID                      HOSTNAME        ROLES
i-0a4d964bb7fe00d07     10.99.32.12     vault-3
i-0741ff1c7ed248537     10.99.32.11     vault-2
i-09eaa8b7912e49e55     10.99.48.18     master
i-0dff3a294bbed44cb     18.203.19.195   bastion
i-061afd10bfea310af     10.99.32.255    worker
i-0ebc1b0691b35347c     10.99.60.148    worker
i-05c9e827f8361cf8f     10.99.42.67     worker
i-0d2677f4f2d93d993     10.99.50.29     etcd-2
i-0e632b371160f3eea     10.99.35.80     etcd-3
i-0a0175e333393b643     10.99.32.10     vault-1
i-0ca52bba05a24def4     10.99.50.45     etcd-1
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0a4d964bb7fe00d07
```
[centos@vault-3 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● kdump.service   loaded failed failed Crash recovery kernel arming
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

2 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0741ff1c7ed248537
```
Warning: Permanently added '10.99.32.11' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 13:29:43 2018 from 89.238.154.226
[centos@vault-2 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● kdump.service   loaded failed failed Crash recovery kernel arming
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

2 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-09eaa8b7912e49e55
```
Last login: Tue Oct  2 13:56:11 2018 from ip-10-99-3-67.eu-west-1.compute.internal
[centos@envnewydd-cluster|master|ip-10-99-48-18 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@envnewydd-cluster|master|ip-10-99-48-18 ~]$
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0dff3a294bbed44cb
```
Last login: Tue Oct  2 13:29:43 2018 from 89.238.154.226
[centos@bastion ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● kdump.service   loaded failed failed Crash recovery kernel arming
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

2 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-061afd10bfea310af
```
Last login: Tue Oct  2 13:53:32 2018 from ip-10-99-3-67.eu-west-1.compute.internal
[centos@envnewydd-cluster|worker|ip-10-99-32-255 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0ebc1b0691b35347c
```
Warning: Permanently added '10.99.60.148' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 13:29:43 2018 from 89.238.154.226
[centos@envnewydd-cluster|worker|ip-10-99-60-148 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```
 `alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-05c9e827f8361cf8f
```
Last login: Tue Oct  2 13:51:18 2018 from ip-10-99-3-67.eu-west-1.compute.internal
[centos@envnewydd-cluster|worker|ip-10-99-42-67 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0d2677f4f2d93d993
```
Last login: Tue Oct  2 14:07:40 2018 from ip-10-99-3-67.eu-west-1.compute.internal
[centos@envnewydd-cluster|etcd-2|ip-10-99-50-29 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0e632b371160f3eea
```
Warning: Permanently added '10.99.35.80' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 13:29:43 2018 from 89.238.154.226
[centos@envnewydd-cluster|etcd-3|ip-10-99-35-80 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0a0175e333393b643
```
Warning: Permanently added '10.99.32.10' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 13:29:43 2018 from 89.238.154.226
[centos@vault-1 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● kdump.service   loaded failed failed Crash recovery kernel arming
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

2 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0ca52bba05a24def4
```
Warning: Permanently added '10.99.50.45' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 13:29:43 2018 from 89.238.154.226
[centos@envnewydd-cluster|etcd-1|ip-10-99-50-45 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.

**Comment by alljames** [comment]
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster instance list          
```
ID			HOSTNAME	ROLES	
i-014e07c0c15e2fd3f 	52.208.150.195 	bastion 
i-06ac1d61541cbe50c 	10.99.50.150 	etcd-3 	
i-0a37efad4a60e6bc1 	10.99.32.10 	vault-1 
i-062cb1ed75e1c7175 	10.99.62.45 	worker 	
i-0d3b44ec3ce9545dc 	10.99.59.191 	worker 	
i-05ce57ddca9c59426 	10.99.39.206 	worker 	
i-0ad631133c1da8786 	10.99.32.11 	vault-2 
i-0c87a1b886eff19a8 	10.99.58.244 	etcd-1 	
i-046d19f7a3509e7f7 	10.99.63.125 	master 	
i-0b4055b8c1fbfb0f8 	10.99.58.167 	etcd-2 	
i-058a5fa5cecb1f913 	10.99.32.12 	vault-3 
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk ssh i-014e07c0c15e2fd3f                                                                                                                                                    
```
Error: unknown command "ssh" for "tarmak"
Run 'tarmak --help' for usage.
unknown command "ssh" for "tarmak"
 alljames  e570  @gosrc-GitHub  simonswine  tarmak  ⚓ 729cc25a8  ERROR  %  tk ssh instance i-014e07c0c15e2fd3f
Error: unknown command "ssh" for "tarmak"
Run 'tarmak --help' for usage.
unknown command "ssh" for "tarmak"
 alljames  e570  @gosrc-GitHub  simonswine  tarmak  ⚓ 729cc25a8  ERROR  %  tk cluster ssh i-014e07c0c15e2fd3f 
Last login: Tue Oct  2 14:38:41 2018 from 89.238.154.226
[centos@bastion ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● kdump.service   loaded failed failed Crash recovery kernel arming
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

2 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@bastion ~]$ logout
Shared connection to 52.208.150.195 closed.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-06ac1d61541cbe50c
```
Warning: Permanently added '10.99.50.150' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 14:38:41 2018 from 89.238.154.226
[centos@envtestfailedunits-cluster|etcd-3|ip-10-99-50-150 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@envtestfailedunits-cluster|etcd-3|ip-10-99-50-150 ~]$ logout
Shared connection to 10.99.50.150 closed.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0a37efad4a60e6bc1
```
Warning: Permanently added '10.99.32.10' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 14:38:41 2018 from 89.238.154.226
[centos@vault-1 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● kdump.service   loaded failed failed Crash recovery kernel arming
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

2 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@vault-1 ~]$ logout
Shared connection to 10.99.32.10 closed.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-062cb1ed75e1c7175
```
Warning: Permanently added '10.99.62.45' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 14:38:41 2018 from 89.238.154.226
[centos@envtestfailedunits-cluster|worker|ip-10-99-62-45 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@envtestfailedunits-cluster|worker|ip-10-99-62-45 ~]$ logout
Shared connection to 10.99.62.45 closed.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0d3b44ec3ce9545dc
```
Warning: Permanently added '10.99.59.191' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 14:38:41 2018 from 89.238.154.226
[centos@envtestfailedunits-cluster|worker|ip-10-99-59-191 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@envtestfailedunits-cluster|worker|ip-10-99-59-191 ~]$ logout
Shared connection to 10.99.59.191 closed.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-05ce57ddca9c59426
```
Warning: Permanently added '10.99.39.206' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 14:38:41 2018 from 89.238.154.226
[centos@envtestfailedunits-cluster|worker|ip-10-99-39-206 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@envtestfailedunits-cluster|worker|ip-10-99-39-206 ~]$ logout
Shared connection to 10.99.39.206 closed.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0ad631133c1da8786
```
Warning: Permanently added '10.99.32.11' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 14:38:41 2018 from 89.238.154.226
[centos@vault-2 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● kdump.service   loaded failed failed Crash recovery kernel arming
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

2 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@vault-2 ~]$ logout
Shared connection to 10.99.32.11 closed.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0c87a1b886eff19a8
```
Warning: Permanently added '10.99.58.244' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 14:38:41 2018 from 89.238.154.226
[centos@envtestfailedunits-cluster|etcd-1|ip-10-99-58-244 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@envtestfailedunits-cluster|etcd-1|ip-10-99-58-244 ~]$ logout
Shared connection to 10.99.58.244 closed.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-046d19f7a3509e7f7
```
Warning: Permanently added '10.99.63.125' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 14:38:41 2018 from 89.238.154.226
[centos@envtestfailedunits-cluster|master|ip-10-99-63-125 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@envtestfailedunits-cluster|master|ip-10-99-63-125 ~]$ logout
Shared connection to 10.99.63.125 closed.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-0b4055b8c1fbfb0f8
```
Warning: Permanently added '10.99.58.167' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 14:38:41 2018 from 89.238.154.226
[centos@envtestfailedunits-cluster|etcd-2|ip-10-99-58-167 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@envtestfailedunits-cluster|etcd-2|ip-10-99-58-167 ~]$ logout
Shared connection to 10.99.58.167 closed.
```
`alljames>e570>@gosrc-GitHub>simonswine>tarmak>⚓729cc25a8` $ tk cluster ssh i-058a5fa5cecb1f913
```
Warning: Permanently added '10.99.32.12' (ECDSA) to the list of known hosts.
Last login: Tue Oct  2 14:38:41 2018 from 89.238.154.226
[centos@vault-3 ~]$ systemctl list-units --state=failed
  UNIT            LOAD   ACTIVE SUB    DESCRIPTION
● kdump.service   loaded failed failed Crash recovery kernel arming
● network.service loaded failed failed LSB: Bring up/down networking

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

2 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@vault-3 ~]$ logout
Shared connection to 10.99.32.12 closed.

**Comment by alljames** [comment]
Summary of results
Test repeated
Parameters: commit 729cc25 used to build tarmak, which was in turn used to
`tarmak init` (a single cluster environment)
`tarmak cluster build image` (generated ami-0f3137fda39f01276)
`tarmak cluster apply` (using ami-0f3137fda39f01276)

```
ID                      HOSTNAME        ROLES       UNITS IN FAILED STATE
i-014e07c0c15e2fd3f 	52.208.150.195 	bastion     kdump       network
i-06ac1d61541cbe50c 	10.99.50.150 	etcd-3                  network
i-0a37efad4a60e6bc1 	10.99.32.10 	vault-1     kdump       network
i-062cb1ed75e1c7175 	10.99.62.45 	worker                  network
i-0d3b44ec3ce9545dc 	10.99.59.191 	worker                  network
i-05ce57ddca9c59426 	10.99.39.206 	worker                  network
i-0ad631133c1da8786 	10.99.32.11 	vault-2     kdump       network
i-0c87a1b886eff19a8 	10.99.58.244 	etcd-1                  network
i-046d19f7a3509e7f7 	10.99.63.125 	master                  network
i-0b4055b8c1fbfb0f8 	10.99.58.167 	etcd-2                  network
i-058a5fa5cecb1f913 	10.99.32.12 	vault-3     kdump       network
```

**Comment by alljames** [comment]
OK, have rebuilt the images and made sure the PR commit was being included - I should have checked that the Makefile was pointing to the correct directory. SSH'd into all instances in a single cluster environment and no failing services to report.

Commit looks good.

/unassign
/assign @simonswine 

```
[centos@master ~]$ systemctl list-units --state=failed
0 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```

Also ran the following commands on one instance
```
[centos@vault-2 ~]$ systemctl list-units --all --state=failed
0 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
[centos@vault-2 ~]$ systemctl list-unit-files --state=failed
UNIT FILE STATE

0 unit files listed.
```

**Pull request merged**
