### PR TITLE
Improve AWS validate/verify

### LINKED ISSUE #154: Improve invalid/missing aws profile value
/kind feature

**What happened**:
If an .aws/credentials profile name `[example]` doesn't match the profile in the tarmak.yml `profile: example` then it fails with this error:

```
FATA[0005] Tarmak exited with an error.                  error="NoCredentialProviders: no valid providers in chain. Deprecated.
   For verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```

**What you expected to happen**:
An error saying there is a missing provider or that the provider is missing an entry in `.aws/credentials`

**How to reproduce it (as minimally and precisely as possible)**:
Use a wonky `profile: value` in your aws authenticated tarmak config

### LINKED ISSUE #282: Verify if all subnets' AZs are actually existing in AWS
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:

We should validate subnets only in `Verify()`, currently we are doing it as part of `Validate()`

**What you expected to happen**:

Fail with an error if an invalid AZ is set

### PR DESCRIPTION
**Pull request by MattiasGees**
**What this PR does / why we need it**:
- This moves everything that does an external call to the verify method.
- Check if our AWS credentials are correctly setup is the first verify step and it will fail on that if it doesn't work. AWS unfortunately doesn't have a better way of checking our AWS credentials and getting a better error back is really hard.
- Run verify step on provider check and not only the validate step
- Fails a bit better now
```
validation failed: 1 error occurred:

* There was a problem with veryfing your AWS credentials: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #154 
fixes #282 

This also tackles part of the problem in #280 

**Special notes for your reviewer**:

**Release note**:

```release-note
Improve verification of AWS credentials on provider creation
```

### CODE REVIEW

**Comment by charlieegan3** [comment]
I took a look over the code. Looked fine at a glance.

For testing, I ran a plan - worked ok.

I then ran a tarmak init and got the following panic that doesn't happen on master:

```
tarmak|./tarmak_local_build init                                                                                                                                                              
Select environment or create new                                                                                                                                                              
  1) charlie (unavailable as single cluster env)                                                                                                                                              
  2) create new environment (default)                                                                                                                                                         
> 2                                                                                                                                                                                           
Select an existing provider or create a new one                                                                                                                                               
  1) amazon[jetstack-amazon]                                                                                                                                                                  
  2) Create a new provider (default)                                                                                                                                                          
> 2                                                                                                                                                                                           
Enter a unique name for this provider [a-z0-9-]+                                                                                                                                              
> amazoncharlie                                                                                                                                                                               
Select a cloud                                                                                                                                                                                
  1) amazon (default)                                                                                                                                                                         
  2) azure                                                                                                                                                                                    
> 1                                                                                                                                                                                           
Where should the credentials for this provider come from?                                                                                                                                     
  1) Amazon CLI auth, using environment variables or profiles in '~/.aws' (default)                                                                                                           
  2) read from Vault path                                                                                                                                                                     
> 2                                                                                                                                                                                           
Which Vault path should be used for Amazon credentials?                                                                                                                                       
> jetstack/aws/jetstack-dev/sts/admin                                                                                                                                                         
Which prefix should be used for the state buckets and DynamoDB tables? ([a-z0-9-]+, should be globally unique) (default 'amazoncharlie-tarmak-')                                              
>                                                                                                                                                                                             
Which public DNS zone should be used? (the DNS zone will be created if it does not exist and it must be delegated from the root)                                                              
> develop.tarmak.org                                                                                                                                                                          
                                                                                                                                                                                              
name: amazoncharlie                                                                                                                                                                           
cloud: amazon                                                                                                                                                                                 
public_zone: develop.tarmak.org                                                                                                                                                               
bucket_prefix: amazoncharlie-tarmak-                                                                                                                                                          
vault_path: jetstack/aws/jetstack-dev/sts/admin                                                                                                                                               
                                                                                                                                                                                              
Continue with this provider? [Y/n] y                                                                                                                                                          
Enter a unique name for this environment ([a-z0-9]+) - e.g. dev/staging/prod                                                                                                                  
> things                                                                                                                                                                                      
What is the project name? (default 'tarmak-playground')                                                                                                                                       
> things                                                                                                                                                                                      
Provide a contact mail address for the project administrator                                                                                                                                  
> things@charlie.com                                                                                                                                                                          
In which region should this environment reside?     
  1) ap-northeast-1                            
  2) ap-northeast-2                            
  3) ap-south-1                                
  4) ap-southeast-1                            
  5) ap-southeast-2                            
  6) ca-central-1                              
  7) eu-central-1                              
  8) eu-west-1                                 
  9) eu-west-2
 10) eu-west-3
 11) sa-east-1
 12) us-east-1
 13) us-east-2
 14) us-west-1
 15) us-west-2
> 8

name: things
location: eu-west-1
provider: amazon[amazoncharlie]

Continue with this environment? [Y/n] Y
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xf27b54]

goroutine 1 [running]:
github.com/jetstack/tarmak/pkg/tarmak/environment.(*Environment).Validate(0xc420024400, 0xc420caf748, 0x1)
        /home/charlieegan3/Code/go/src/github.com/jetstack/tarmak/pkg/tarmak/environment/environment.go:290 +0xa4
github.com/jetstack/tarmak/pkg/tarmak/initialize.(*Initialize).InitEnvironment(0xc4208f6080, 0xc42091f928, 0x1, 0x0, 0x0)
        /home/charlieegan3/Code/go/src/github.com/jetstack/tarmak/pkg/tarmak/initialize/initialize.go:180 +0x619
github.com/jetstack/tarmak/pkg/tarmak/initialize.(*Initialize).GetEnvironment(0xc4208f6080, 0x0, 0x0, 0x460da2, 0x6)
        /home/charlieegan3/Code/go/src/github.com/jetstack/tarmak/pkg/tarmak/initialize/initialize.go:410 +0x580
github.com/jetstack/tarmak/pkg/tarmak/initialize.(*Initialize).InitCluster(0xc4208f6080, 0xc4208093f0, 0x3eebe20, 0xc4200e6000, 0x3ede580)
        /home/charlieegan3/Code/go/src/github.com/jetstack/tarmak/pkg/tarmak/initialize/initialize.go:266 +0x76
github.com/jetstack/tarmak/pkg/tarmak.(*Tarmak).CmdClusterInit(0xc4208093f0, 0x3cff838, 0xc4208093f0)
        /home/charlieegan3/Code/go/src/github.com/jetstack/tarmak/pkg/tarmak/tarmak.go:179 +0x9f
github.com/jetstack/tarmak/cmd/tarmak/cmd.glob..func9(0x620f7c0, 0x6444d18, 0x0, 0x0)
        /home/charlieegan3/Code/go/src/github.com/jetstack/tarmak/cmd/tarmak/cmd/cluster_init.go:18 +0x75
github.com/jetstack/tarmak/vendor/github.com/spf13/cobra.(*Command).execute(0x620f7c0, 0x6444d18, 0x0, 0x0, 0x620f7c0, 0x6444d18)
        /home/charlieegan3/Code/go/src/github.com/jetstack/tarmak/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
github.com/jetstack/tarmak/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x6211b60, 0x7ffd68b1ae71, 0xc4200ec010, 0xc420599df0)
        /home/charlieegan3/Code/go/src/github.com/jetstack/tarmak/vendor/github.com/spf13/cobra/command.go:843 +0x30a
github.com/jetstack/tarmak/vendor/github.com/spf13/cobra.(*Command).Execute(0x6211b60, 0xc4200ec010, 0x1)
        /home/charlieegan3/Code/go/src/github.com/jetstack/tarmak/vendor/github.com/spf13/cobra/command.go:791 +0x2b
github.com/jetstack/tarmak/cmd/tarmak/cmd.Execute(0xc4200ec010, 0x1, 0x1)
        /home/charlieegan3/Code/go/src/github.com/jetstack/tarmak/cmd/tarmak/cmd/root.go:56 +0x16c
main.main()
        /home/charlieegan3/Code/go/src/github.com/jetstack/tarmak/cmd/tarmak/main.go:22 +0x10b
```

**Comment by charlieegan3** [comment]
I can't replicate this. I expect the error I was getting was fixed in https://github.com/jetstack/tarmak/pull/374/commits/5b4e1aa325f9e2f485230b7967c9a8cf9a1874f0 

/lgtm

**Comment by simonswine** [comment]
Just a minor thing: can you refactor that all errors start lower case

/unassign
/assign @MattiasGees

**Comment by MattiasGees** [comment]
@simonswine fixed
/unassign
/assign @simonswine

**Pull request merged**
