### PR TITLE
Use vault-helper dry run ensure

### PR DESCRIPTION
**Pull request by JoshVanL**
```release-note
Use vault-helper dry run ensure
```

/assign
/hold

### CODE REVIEW

**Comment by simonswine** [comment]
I am not too sure if this is expected

* Created cluster with this PR
* Ran tarmak cluster plan. no changes 
* SSH into vault and removed k8s secret backend: `vault secrets disable <env>-cluster/pki/k8s`
* Ran tarmak cluster plan, changes but not on the cluster resource
* Ran tarmak cluster plan. no changes 

So there is definitely something going on, not just a dry run

/assign @JoshVanL 
/unassign
/hold

**Comment by JoshVanL** [comment]
@simonswine  this behavior should now be fixed

/unassign
/assign @simonswine

**Comment by simonswine** [comment]
/approve
/lgtm

Thanks @JoshVanL, works fine for me

**Pull request merged**
