### PR TITLE
Encrypt puppet tar ball

### LINKED ISSUE #467: S3 bucket encryption
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
At the moment the S3 buckets created by tarmak for the kubernetes state store and the vault unsealer secrets are not encrypted

**What you expected to happen**:
Encrypted bucket

**How to reproduce it (as minimally and precisely as possible)**:
Setup a k8s cluster with Tarmak

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by JoshVanL**
**What this PR does / why we need it**:
KMS encrypt consul backups and puppet tar balls.

fixes #467 

Special notes:
Requires apply in --wing-dev-mode

```release-note
Encrypt S3 puppet tar ball and consul backup buckets.
```

### CODE REVIEW

**Comment by simonswine** [comment]
This is still not working with the old wing. We have to make sure we support after this is merged the new way and the old one till at least 0.6. tarmak. Also need to be rebased before it's working because of the issues in the tarmak master.


/assign @JoshVanL 
/unassign

**Comment by JoshVanL** [comment]
@simonswine Not sure what you mean, I think we still are supporting it.
$ tarmak_0.4.1 cluster apply 
$ tarmak_467 cluster apply --wing-dev-mode works for me
Masters and workers wing are still pointing to the old location and run fine.

We have a 'legacy' puppet location until 0.6 which is being updated through taints.

**Comment by simonswine** [comment]
/assign @JoshVanL 
/unassign @simonswine 

Have you seen those errors as well:

```
DEBU[0030] module.state.aws_s3_bucket.secrets: Destroying... (ID: tarmak-csire-eu-west-1-secrets)  app=tarmak module=terraform std=out
DEBU[0031]                                          app=tarmak module=terraform std=err
DEBU[0031] Error: Error applying plan:  app=tarmak module=terraform std=err
DEBU[0031]                                               app=tarmak module=terraform std=err
DEBU[0031] 1 error occurred:                             app=tarmak module=terraform std=err
DEBU[0031]      * module.state.aws_s3_bucket.secrets (destroy): 1 error occurred:  app=tarmak module=terraform std=err
DEBU[0031]      * aws_s3_bucket.secrets: Error deleting S3 Bucket: BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.  app=tarmak module=terraform std=err
DEBU[0031]      status code: 409, request id: 00C49FD3BF0E0507, host id: WMV4zxI6s7bC2c/5XeAfT4CQ3y04M+DxpGtk0dRXFG4VLj/fCFvWuCcgeakJciPNDxJsiGmiic0= "tarmak-csire-eu-west-1-secrets"  app=tarmak module=terraform std=err
```

I guess a force destroy on the bucket will help

**Comment by JoshVanL** [comment]
@simonswine 
Hmm I don't think so, what did you do to reproduce it? Maybe different tarmak versions on the hub and cluster?

**Comment by simonswine** [comment]
- Create single cluster normally
- Change e.g. Kubernetes version in tarmak.yaml
- Apply through `tarmak cluster apply -C`

The new puppet.tar.gz is not being cleanup ed by the destroy. Down to the new hash not being in the tf state

**Comment by JoshVanL** [comment]
@simonswine Yep, just released, that makes sense. The force flag already exists on the destroy command.  Do we want to think about cleaning up these resources ourselves?

**Comment by simonswine** [comment]
/assign @JoshVanL 

One final rebase :grimacing:

**Pull request merged**
