### PR TITLE
Add Jenkins module to Terraform stack

### LINKED ISSUE #173: Add Jenkins module to Terraform stack
We need to add a Jenkins module to the Terraform stack to configure Jenkins when bringing up environments. The following example `tarmak.yaml` snippet contains a typical Jenkins configuration for environments A and B:

- Jenkins will run in the environment A's hub as an instance pool
- Environment B references A's Jenkins instance
- All clusters in the B environment use A's Jenkins instance
- Any subsequent instances (e.g. prod) will also use A's Jenkins instance

```
environments:
- contact: tech@jetstack.io
  location: eu-west-2
  metadata:
    creationTimestamp: "2018-04-06T13:03:00Z"
    name: A
  privateZone: tarmak.local
  project: kubernetes
  provider: xyz-A
  jenkins:
    url: https://jenkins-in-A
    username: password
    password: (read from tarmak-config if not specified)
    prefix: (folder prefix, default empty) 
- contact: tech@jetstack.io
  location: eu-west-2
  metadata:
    creationTimestamp: "2018-04-06T13:03:00Z"
    name: B
  privateZone: tarmak.local
  project: kubernetes
  provider: xyz-B
  jenkins:
    url: https://jenkins-in-B
    username: password
    password: (read from tarmak-config if not specified)
    prefix: (folder prefix, default empty)
```

To configure HTTPS on the Jenkins loadbalancer, add the annotation `tarmak.io/jenkins-certificate-arn: <CRN>` to the metadata of the Jenkins instance pool.

### PR DESCRIPTION
**Pull request by MattiasGees**
**What this PR does / why we need it**:
Follow up of @dippynark work #190. This adds Jenkins to the stack.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fixes #173 
**Special notes for your reviewer**:
This works further on the great work of @dippynark of #190 

**Release note**:

```release-note
Add support to install Jenkins with Tarmak
```

### CODE REVIEW

**Comment by dippynark** [comment]
@MattiasGees After adding the Jenkins nodePools, I am getting:
```
$ tarmak clusters apply       (gke_jetstack-workshops_europe-west2-a_jetstack-workshops/default)
DEBU[0002] no availability zones specified selecting zone: eu-west-1a  app=tarmak provider_name=aws
INFO[0003] running apply                                 app=tarmak cluster=hub environment=test
DEBU[0003] created temporary directory: /var/folders/3k/xg9qp_d150l9kpp42_1yf0900000gn/T/tarmak-assets534955550
DEBU[0004] restored assets into directory: /var/folders/3k/xg9qp_d150l9kpp42_1yf0900000gn/T/tarmak-assets534955550
DEBU[0006] rpc server started                            app=tarmak
DEBU[0006] Initializing modules...           app=tarmak module=terraform std=out
DEBU[0006] - module.state                                app=tarmak module=terraform std=out
DEBU[0006] - module.network                              app=tarmak module=terraform std=out
DEBU[0006] - module.bastion                              app=tarmak module=terraform std=out
DEBU[0006] - module.jenkins                              app=tarmak module=terraform std=out
DEBU[0006] - module.vault                                app=tarmak module=terraform std=out
DEBU[0006]                                               app=tarmak module=terraform std=out
DEBU[0006] Initializing the backend...       app=tarmak module=terraform std=out
DEBU[0009]                                               app=tarmak module=terraform std=out
DEBU[0009] Initializing provider plugins...  app=tarmak module=terraform std=out
DEBU[0011]                                               app=tarmak module=terraform std=out
DEBU[0011] Terraform has been successfully initialized!  app=tarmak module=terraform std=out
DEBU[0016]                                          app=tarmak module=terraform std=err
DEBU[0016] Error: Required variable not set: jenkins_ami  app=tarmak module=terraform std=err
DEBU[0016]                                               app=tarmak module=terraform std=err
DEBU[0016]                                   app=tarmak module=terraform std=err
ERRO[0016] Tarmak exited with an error: exit status 1    error="exit status 1"
```

**Comment by MattiasGees** [comment]
@dippynark what is your nodepool definition look like?

**Comment by dippynark** [comment]
@MattiasGees 
```
instancePools:
  - image: centos-puppet-agent-latest-kernel
    maxCount: 1
    metadata:
      creationTimestamp: "2018-04-17T14:57:01Z"
      name: jenkins
    minCount: 1
    size: large
    type: jenkins
    volumes:
    - metadata:
        creationTimestamp: "2018-04-17T14:57:01Z"
        name: root
      size: 16Gi
      type: ssd
    - metadata:
        creationTimestamp: "2018-04-17T14:57:01Z"
        name: data
      size: 16Gi
      type: ssd
```

**Comment by MattiasGees** [comment]
@dippynark I tested bringing up a cluster from scratch and I was able to do that without any problems. I didn't ran in any error. Only difference between your config and mine, is that I have an annotation defined for the SSL certificate.

**Comment by dippynark** [comment]
@MattiasGees It's because I put `centos-puppet-agent-latest-kernel` in my config which has changed to `centos-puppet-agent`. The relevant code is in `pkg/tarmak/cluster/cluster.go` near line 408. Everything worked after I fixed my config but have created an issue as we probably want a more descriptive error if something similar happens again - https://github.com/jetstack/tarmak/issues/243

**Comment by dippynark** [comment]
The jenkins instance is also showing up as `etcd-1` in `tarmak clusters instances list`:
```
ID                      HOSTNAME        ROLES
i-09013a901739d58d4     10.99.48.253    etcd-1
i-0a3a59b860729c44a     34.248.239.119  bastion
i-06953ea3432ceebfb     10.99.32.12     vault-3
i-07387bb651a9f83a6     10.99.32.10     vault-1
i-041a4f54e682d2d17     10.99.32.11     vault-2
```
The instance is being called `jenkins-<environment>-<cluster>-k8s-etcd-1` instead of `<cluster>-<environment>-jenkins`. A tag is also being added to Jenkins called `Etcd_Volume_Attach=jenkins-test-hub-k8s-etcd-1` so I think the stateful part of the templating needs to be tailored to jenkins instead of just etcd

**Comment by MattiasGees** [comment]
@dippynark this is fixed now

**Comment by dippynark** [comment]
@MattiasGees I am getting the following when spinning up a hub:
```
DEBU[0275] Error: Error applying plan:  app=tarmak module=terraform std=err
DEBU[0275]                                               app=tarmak module=terraform std=err
DEBU[0275] 1 error occurred:                             app=tarmak module=terraform std=err
DEBU[0275]                                               app=tarmak module=terraform std=err
DEBU[0275] * module.jenkins.aws_elb.jenkins: 1 error occurred:  app=tarmak module=terraform std=err
DEBU[0275]                                               app=tarmak module=terraform std=err
DEBU[0275] * aws_elb.jenkins: ValidationError: Secure Listeners need to specify a SSLCertificateId  app=tarmak module=terraform std=err
```
I haven't specified a certificate ARN in my config but it seems to be trying to deploy an ELB for Jenkins serving over HTTPS

**Pull request merged**
