### PR TITLE
Adds Jenkins instance pool tests to tarmak_test.go

### PR DESCRIPTION
**Pull request by JoshVanL**
Includes Jenkins instance pool into tarmak_test.go

```release-note
NONE
```

### CODE REVIEW

**Comment by simonswine** [comment]
My concern is/was we did not call `terraform validate` on those stacks so the error was not catched.

You can have a look at my code but that will fail as `terraform init` blocks as it wants some connection to the state bucket

https://github.com/jetstack/tarmak/commit/1f00bd849459a0d910f3e4c63fdc1effc5d98a41

**Comment by JoshVanL** [comment]
@simonswine Guess we should have some flag for controlling off/on line tests to skip or run this

**Comment by simonswine** [comment]
I guess maybe if we don't configure the remote state (and use local) it should work, I will create an inssue for that 

/assign @simonswine

**Pull request merged**
