### PR TITLE
Add navigator docs section

### PR DESCRIPTION
**Pull request by charlieegan3**
Fixes https://github.com/jetstack/tarmak/issues/429

Signed-off-by: charlieegan3 <charlieegan3@users.noreply.github.com>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Add example docs section on installing jetstack/navigator
```

### CODE REVIEW

**Comment by simonswine** [comment]
Thanks @charlieegan3 

/assign @charlieegan3 
/unassign 

Can you verifiy if a elasticsearch cluster works. (I guess there might be issues with PodSecurityPolicy)

**Comment by charlieegan3** [comment]
Certainly, going to need some bigger nodes too by the looks of it...

**Comment by charlieegan3** [comment]
I have now completed the ES example in the navigator docs. The only issue I ran into was space in my cluster.

I followed [this guide](https://www.elastic.co/guide/en/kibana/current/tutorial-load-dataset.html) to load in a good amount of data. This left me with the following indices:

```
tarmak $ curl -X GET "localhost:9200/_cat/indices?v"                                           
health status index                         uuid                   pri rep docs.count docs.deleted store.size pri.store.size                                                                  
green  open   .watcher-history-6-2018.09.25 DuBpl7t-QHSVraZ8QYe-zg   1   1        204            0    513.2kb          330kb                                                                  
green  open   bank                          -RqyDHVFS8yOptWt9NhKrQ   5   1       1000            0      1.2mb        640.3kb                                                                  
green  open   logstash-2015.05.20           qlGT83-sQkiIm8sMpZr1BA   5   1       4750            0     66.8mb         34.2mb                                                                  
green  open   logstash-2015.05.19           uP_qVGj1Q5uTFW1HBDJg3g   5   1       4624            0     69.6mb         36.3mb                                                                  
green  open   logstash-2015.05.18           nM2vTQkyRVKbVHJQzDm9qA   5   1       4631            0     66.5mb         34.4mb                                                                  
green  open   .triggered_watches            GVpoaeQkSXmQwHM1RkOP1Q   1   1          0            0     18.9kb          8.1kb                                                                  
green  open   .watches                      j-Jo50QKRmygfv9fJ-gHDQ   1   1          4            0     31.1kb         11.4kb                                                                  
green  open   .monitoring-es-6-2018.09.25   FNGEAfF1SHmGd6b4-ks2gA   1   1       4128          116      6.1mb          2.9mb                                                                  
green  open   shakespeare                   n2SsGq5_T7KMSJ2gRXr7vw   5   1     111396            0     60.2mb         30.3mb                                               
```
After this the cluster was healthy:

```
tarmak $ curl -X GET "localhost:9200/_cluster/health" | jq                                                                                                                         
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                               
                                 Dload  Upload   Total   Spent    Left  Speed                                                                                                                 
100   391  100   391    0     0   3759      0 --:--:-- --:--:-- --:--:--  3796                                                                                                                
{                                                                                                                                                                                             
  "cluster_name": "elasticsearch",                                                                                                                                                            
  "status": "green",                                                                                                                                                                          
  "timed_out": false,                                                                                                                                                                         
  "number_of_nodes": 5,                                                                        
  "number_of_data_nodes": 2,                                                                                                                                                                    "active_primary_shards": 29,                                                                                                                                                                  "active_shards": 58,                                                                         
  "relocating_shards": 0,                                                                      
  "initializing_shards": 0,                                                                    
  "unassigned_shards": 0,                                                                      
  "delayed_unassigned_shards": 0,              
  "number_of_pending_tasks": 0,                
  "number_of_in_flight_fetch": 0,              
  "task_max_waiting_in_queue_millis": 0,       
  "active_shards_percent_as_number": 100       
}                                              
```

And I was able to query the data:

```
tarmak $ curl -XPOST 'localhost:9200/bank/_search?pretty' -d '                                                                                                                                
{                                                                                                                                                                                             
  "query": { "match_all": {} },                                                                                                                                                               
  "_source": ["account_number", "balance"]                                                                                                                                                    
}'                                                                                                                                                                                            
{                                                                                                                                                                                             
  "took" : 3,                                                                                                                                                                                 
  "timed_out" : false,                                                                                                                                                                        
  "_shards" : {                                                                                                                                                                               
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1000,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "bank",
        "_type" : "account",
        "_id" : "25",
        "_score" : 1.0,
        "_source" : {
          "account_number" : 25,
          "balance" : 40540
        }
      },
...
```

I added a short note to the docs about the size of the nodes.

Would you suggest doing any more testing @simonswine ?

/assign @simonswine 
/unassign

**Comment by simonswine** [comment]
No thank you that looks good to me. I might need to ask for rebase after the baylon features are merged

**Pull request merged**
