### PR TITLE
Better image build control

### LINKED ISSUE #599: Better control over `cluster image build`
/kind feature

Right now it seems that `image build` will just re-build all images that are listed in the current cluster instance pools. We should provide a way to more finely control this behavior.

IMHO, default behavior should not re-build images that are already existing.
This can be overwritten with an override/force flag.
Enable to select a subset of images to build.

### PR DESCRIPTION
**Pull request by JoshVanL**
As we are adding more base images for different instance roles we should have better control over building these images. This adds the ability to only build missing images, specific images or all images. This pairs with the images destroy sub-command.

fixes #599 

```release-note
Add better `cluster images build` CLI behavior
```

/assign @MattiasGees

### CODE REVIEW

**Comment by MattiasGees** [comment]
works

/lgtm
/approve
/unassign
/assign @simonswine

**Comment by JoshVanL** [comment]
@simonswine good catch, forgot to check for matching encryption

**Comment by JoshVanL** [comment]
@simonswine good catch, forgot to check for matching encryption

**Pull request merged**
