### PR TITLE
Validate Jenkins as a valid instance pool for hub

### PR DESCRIPTION
**Pull request by MattiasGees**
**What this PR does / why we need it**:
It needs to be possible to setup a Jenkins server in the hub.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Jenkins is a valid instancepool for hub
```

### CODE REVIEW

**Comment by simonswine** [comment]
/assign @MattiasGees 
/unassign

@MattiasGees please sign of the commit for the DCO

**Comment by MattiasGees** [comment]
Signed
/unassign
/assign @simonswine

**Comment by simonswine** [comment]
Thanks @MattiasGees 

/lgtm

**Pull request merged**
