### PR TITLE
Fluentbit beaker tests

### LINKED ISSUE #238: Add acceptance tests for aws-es-proxy
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**Description**: We need acceptance test when running fluent-bit with aws-es-proxy. The following needs an ES stub to test against:

```
require 'spec_helper_acceptance'

describe '::fluent_bit' do
  pp = <<-EOS
fluent_bit::output{"test1":
  config => { 
    "elasticsearch" => {
      "host" => "search-logs-example.eu-west-1.es.amazonaws.com",
      "port" => 443,
      "tls" => true,
      "tlsVerify" => true,
      "amazonESProxy" => {
        "port" => 9200
      },
    },
    "types" => ["all"],
  },
}
fluent_bit::output{"test2":
  config => { 
    "elasticsearch" => {
      "host" => "search-logs-example.eu-west-1.es.amazonaws.com",
      "port" => 443,
      "tls" => true,
      "tlsVerify" => true,
      "logstashPrefix" => "testprefix",
      "amazonESProxy" => {
        "port" => 9201
      },
    },
    "types" => ["all"],
  },
}
EOS

  before(:all) do
    # assign private ip addresses
    hosts.each do |host|
      # clear firewall
      on host, "iptables -F INPUT"
    end
  end

  it 'should setup fluent bit without errors based on the example' do
    hosts.each do |host|
      apply_manifest_on(host, pp, :catch_failures => true)
      expect(
        apply_manifest_on(host, pp, :catch_failures => true).exit_code
      ).to be_zero
    end
  end
end
```

### PR DESCRIPTION
**Pull request by JoshVanL**
/assign
fixes #238 

```release-note
Adds fluent-bit acceptance tests
```

### CODE REVIEW

**Comment by JoshVanL** [comment]
/unassign
/assign @simonswine 

Not sure why this is failing

**Comment by simonswine** [comment]
/assign @JoshVanL 

Can you have a look, you won't be able to LGTM, but just to double check

**Pull request merged**
