### PR TITLE
Ensure volumes are correctly mounted for vault instances

### LINKED ISSUE #697: Vault data disks not mounted
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:
Vault clusters don't mount and use their data EBS volume. The disk gets created in AWS but doesn't get mounted to the vault instance.

**What you expected to happen**:
2 disks mounted on every instance in the vault cluster.

**How to reproduce it (as minimally and precisely as possible)**:
`tarmak init`
`tarmak apply`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration**:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by JoshVanL**
Fixes the puppet to actually invoke the volume attachment for vault instances and assigns DescribeVolumes policy

```release-note
NONE
```

fixes #697

### CODE REVIEW

**Comment by JoshVanL** [comment]
sorry @mattbates !
/unassign @mattbates 
/assign @MattiasGees

**Comment by MattiasGees** [comment]
Tested it and it works
```
lsblk -a
NAME        MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0  16G  0 disk
└─nvme0n1p1 259:1    0  16G  0 part /
nvme1n1     259:2    0  10G  0 disk /var/lib/consul
```
/lgtm
/assign @simonswine

**Comment by simonswine** [comment]
Thank you @JoshVanL

/approve
/lgtm

**Pull request merged**
