### PR TITLE
Removes unused stack related parameters

### LINKED ISSUE #416: Remove unused parameters
> /kind bug

**What happened**:

We have currently still the stacks options on the cluster apply/destroy command. Those options are from before our terraform stacks where merged.

**What you expected to happen**:

Tarmak no longer supporting those and error once they are used

### PR DESCRIPTION
**Pull request by JoshVanL**
**What this PR does / why we need it**:
There was still mention of the now non-existent flags in unused parameters for cluster and destroy flags. These have been removed.

fixes #416 

```release-note
NONE
```

/assign @simonswine

### CODE REVIEW

**Comment by simonswine** [comment]
The file generation changes are now in the master, can you rebase this PR and run `hack/update-codgen.sh`

/assign @JoshVanL 
/unassign

**Comment by MattiasGees** [comment]
Thx looks good and works :)
/lgtm

/unassign
/assign @simonswine

**Pull request merged**
