### PR TITLE
Automated cherry pick of #247 #101 #287 #288 #293 #285 #299 #301 #304 #267 #305 #306 #326 #323 #322 #327 #330 #329 #346 #338 #313 #300 #296 #347 #295 #344 #235 #361 #365 #345 #343 #325 #336 #321 #371 #364 #378

### PR DESCRIPTION
**Pull request by dippynark**
Cherry pick of #247 #101 #287 #288 #293 #285 #299 #301 #304 #267 #305 #306 #326 #323 #322 #327 #330 #329 #346 #338 #313 #300 #296 #347 #295 #344 #235 #361 #365 #345 #343 #325 #336 #321 #371 #364 #378 on release-0.4.

#247: Write ssh config at tarmak initialisation to ensue
#101: Deal with dynamic number of public subnets
#287: Add binary compression to the release builds
#288: Remove -N flag as we are not running a remote command and
#293: Add docs for additional IAM policies
#285: Refactor validate and verify
#299: Upgrade centos to the latest version 7.3
#301: Fix docker slice drop-in by changing quoting and file type
#304: Fix stateful instance naming
#267: Add addon documentation
#305: Upgrade sphinx and base image
#306: Cluster and instance pool should within IAM additional
#326: Fix config parsing
#323: Update terraform to 0.11.7
#322: Pass through etcd instance pool min count to puppet
#327: Add basic docs about apiserver
#330: Fix duplicate ELB name error
#329: Remove unneeded input for Jenkins instance size
#346: Use latest versions of CA
#338: Add security group to allow cluster autoscaler scraping
#313: Fix etcd mount race
#300: Change cgroup drive to cgroupfs
#296: Increase kubelet resource reservations
#347: Adds validation check to ensure instance types in
#295: Start of kube2iam docs
#344: Adds hub remote state verification for multi-clusters
#235: Implements vault-helper dry run and ensure on new tarmak
#361: Use bastion and vault instance type from config
#365: Scrape controller-managers and schedulers
#345: Upgrade Tiller puppet module and docs
#343: Upgrade Dashboard and add RBAC support
#325: Autoscaling arbitrary worker pools
#336: Remove internal worker ELB
#321: Remove Jenkins volume from state module
#371: Revert "vault-helper dry run and delete"
#364: Update vault-helper to 0.9.13
#378: Prepare hub before terraforming other clusters

```release-note
cherry-pick fixes to 0.4 release
```

### CODE REVIEW

**Comment by simonswine** [comment]
I have tested it on a single environment. All looking good IMHO

@dippynark let me know how your multi cluster went and assign it to me

**Comment by dippynark** [comment]
@simonswine yeah everything green
/assign @simonswine

**Pull request merged**
