### PR TITLE
Increases vault max_lease_ttl to 5 years

### PR DESCRIPTION
**Pull request by JoshVanL**
Signed-off-by: JoshVanL <vleeuwenjoshua@gmail.com>

/assign @simonswine 

```release-note
Increase vault's max_lease_ttl to 5 years
```

### CODE REVIEW

**Comment by simonswine** [comment]
Why is this necessary? Is it not enough to do that using `vault auth tune /token`?

**Comment by JoshVanL** [comment]
@simonswine  Yes should be
/close

**Pull request closed without merging**
