### PR TITLE
Fix latest kernel packer image

### PR DESCRIPTION
**Pull request by simonswine**
```release-note
Make sure centos-puppet-agent-latest-kernel is booting into the right kernel
```

### CODE REVIEW

**Comment by simonswine** [comment]
@JoshVanL this seems to be something I introduced through #649

**Comment by alljames** [comment]
Have tested this by specifying `centos-puppet-agent-latest-kernel` in `tarmak.yaml`, building an AMI and spinning up a Tarmak cluster.  I can confirm that SSHing into each instance and running `uname -a` shows that all instances are running the `4.19.8-1.el7.elrepo.x86_64` kernel, i.e. the [latest stable kernel](https://www.kernel.org/)

/lgtm

**Pull request merged**
