### PR TITLE
Update vault-helper to 0.9.13

### LINKED ISSUE #363: Panic during cluster apply
**Is this a BUG REPORT or FEATURE REQUEST?**
/kind bug

**What happened**:
Tarmak will panic during a single cluster apply. This is during a ensure dry run against vault-helper.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x2f817ac]

goroutine 156 [running]:
github.com/jetstack/tarmak/vendor/github.com/jetstack/vault-helper/pkg/kubernetes.(*Kubernetes).ensureDryRunPKIRolesEtcd(0xc420b9b6c0, 0xc4209533b0, 0x41901e0, 0xc420a33630, 0xc4207bdf00)
        /home/christian/.golang/packages/src/github.com/jetstack/tarmak/vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes_pki_roles.go:189 +0xac
github.com/jetstack/tarmak/vendor/github.com/jetstack/vault-helper/pkg/kubernetes.(*Kubernetes).EnsureDryRun(0xc420b9b6c0, 0x3f93220, 0xc420c74860, 0x0)
        /home/christian/.golang/packages/src/github.com/jetstack/tarmak/vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes.go:289 +0x199
github.com/jetstack/tarmak/pkg/terraform/providers/tarmak/rpc.(*tarmakRPC).VaultClusterStatus(0xc420c74840, 0xc420188af0, 0xc4201d4970, 0x0, 0x0)
        /home/christian/.golang/packages/src/github.com/jetstack/tarmak/pkg/terraform/providers/tarmak/rpc/vault_cluster_status.go:74 +0x785
reflect.Value.call(0xc420bee0c0, 0xc420e23170, 0x13, 0x3dfe1d7, 0x4, 0xc420092f18, 0x3, 0x3, 0xc420ece240, 0x43d094, ...)
        /home/christian/.golang/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc420bee0c0, 0xc420e23170, 0x13, 0xc42018ff18, 0x3, 0x3, 0xc420a0d810, 0xffffffffffffffff, 0xc42018ffb0)
        /home/christian/.golang/go/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc4207e2f80, 0xc420937310, 0xc420a0c010, 0xc420a0c030, 0xc420224300, 0xc420552000, 0x3221820, 0xc420188af0, 0x16, 0x3221860, ...)
        /home/christian/.golang/go/src/net/rpc/server.go:384 +0x14e
created by net/rpc.(*Server).ServeCodec
        /home/christian/.golang/go/src/net/rpc/server.go:480 +0x43a
```

**What you expected to happen**:
Not panic.

**How to reproduce it (as minimally and precisely as possible)**:
Single cluster, `tarmak cluster apply`

/assign

### PR DESCRIPTION
**Pull request by JoshVanL**
**What this PR does / why we need it**:
Ensure dry run was panicking due to a logic error in vault-helper. This PR upgrades vault-helper to fix this issue. 

fixes #363 

```release-note
Upgrade vault-helper to 0.9.13
```

/assign @simonswine

### CODE REVIEW

**Comment by simonswine** [comment]
I am still getting this error:

single cluster env

```
DEBU[0481] Error: Error applying plan:  app=tarmak module=terraform std=err
DEBU[0481]                                               app=tarmak module=terraform std=err
DEBU[0481] 1 error occurred:                             app=tarmak module=terraform std=err
DEBU[0481]                                               app=tarmak module=terraform std=err
DEBU[0481] * module.vault.tarmak_vault_cluster.vault: 1 error occurred:  app=tarmak module=terraform std=err
DEBU[0481]                                               app=tarmak module=terraform std=err
DEBU[0481] * tarmak_vault_cluster.vault: call to Tarmak.VaultClusterStatus failed: vault cluster is not ready: 2 errors occurred:  app=tarmak module=terraform std=err
DEBU[0481]                                               app=tarmak module=terraform std=err
DEBU[0481] * error listing mounts: Error making API request.  app=tarmak module=terraform std=err
DEBU[0481]                                               app=tarmak module=terraform std=err
DEBU[0481] URL: GET https://127.0.0.1:35205/v1/sys/mounts  app=tarmak module=terraform std=err
DEBU[0481] Code: 403. Errors:                            app=tarmak module=terraform std=err
DEBU[0481]                                               app=tarmak module=terraform std=err
DEBU[0481] * permission denied                           app=tarmak module=terraform std=err
DEBU[0481] * error listing mounts: Error making API request.  app=tarmak module=terraform std=err
DEBU[0481]                                               app=tarmak module=terraform std=err
DEBU[0481] URL: GET https://127.0.0.1:35205/v1/sys/mounts  app=tarmak module=terraform std=err
DEBU[0481] Code: 403. Errors:                            app=tarmak module=terraform std=err
DEBU[0481]                                               app=tarmak module=terraform std=err
DEBU[0481] * permission denied                           app=tarmak module=terraform std=err
DEBU[0481]                                               app=tarmak module=terraform std=err
DEBU[0481] Terraform does not automatically rollback in the face of errors.  app=tarmak module=terraform std=err
DEBU[0481] Instead, your Terraform state file has been partially updated with  app=tarmak module=terraform std=err
DEBU[0481] any resources that successfully completed. Please address the error  app=tarmak module=terraform std=err
DEBU[0481] above and apply again to incrementally change your infrastructure.  app=tarmak module=terraform std=err
DEBU[0481]                                               app=tarmak module=terraform std=err
DEBU[0481]                                   app=tarmak module=terraform std=err
ERRO[0481] Tarmak exited with an error: exit status 1    error="exit status 1"
```

Pre existing vault_root_token file

**Comment by simonswine** [comment]
I can't see how that fixes anything.

I just run into a similar issue:

```
DEBU[0536] Error: Error applying plan:  app=tarmak module=terraform std=err
DEBU[0536]                                               app=tarmak module=terraform std=err
DEBU[0536] 1 error occurred:                             app=tarmak module=terraform std=err
DEBU[0536]                                               app=tarmak module=terraform std=err
DEBU[0536] * module.vault.tarmak_vault_cluster.vault: 1 error occurred:  app=tarmak module=terraform std=err
DEBU[0536]                                               app=tarmak module=terraform std=err
DEBU[0536] * tarmak_vault_cluster.vault: call to Tarmak.VaultClusterStatus failed: vault cluster is not ready: 1 error occurred:  app=tarmak module=terraform std=err
DEBU[0536]                                               app=tarmak module=terraform std=err
DEBU[0536] * error listing mounts: Error making API request.  app=tarmak module=terraform std=err
DEBU[0536]                                               app=tarmak module=terraform std=err
DEBU[0536] URL: GET https://127.0.0.1:41237/v1/sys/mounts  app=tarmak module=terraform std=err
DEBU[0536] Code: 403. Errors:                            app=tarmak module=terraform std=err
DEBU[0536]                                               app=tarmak module=terraform std=err
DEBU[0536] * permission denied                           app=tarmak module=terraform std=err
DEBU[0536]                                               app=tarmak module=terraform std=err
DEBU[0536] Terraform does not automatically rollback in the face of errors.  app=tarmak module=terraform std=err
DEBU[0536] Instead, your Terraform state file has been partially updated with  app=tarmak module=terraform std=err
DEBU[0536] any resources that successfully completed. Please address the error  app=tarmak module=terraform std=err
DEBU[0536] above and apply again to incrementally change your infrastructure.  app=tarmak module=terraform std=err
DEBU[0536]                                               app=tarmak module=terraform std=err
DEBU[0536]                                   app=tarmak module=terraform std=err
ERRO[0536] Tarmak exited with an error: exit status 1    error="exit status 1"
```

**Comment by JoshVanL** [comment]
@dippynark 

In order for the vault to make an ensure during a hub apply I have copied over a resource from the Kubernetes module to vault so it invokes a vault cluster status. It is here: https://github.com/jetstack/tarmak/blob/57530a7c049dd2dd6860c4a6d102a1d182a32580/terraform/amazon/modules/vault/vault_instances.tf#L110

which has come from here:
https://github.com/jetstack/tarmak/blob/57530a7c049dd2dd6860c4a6d102a1d182a32580/terraform/amazon/modules/kubernetes/vault.tf#L1

Because of this though _somethimes_, more often than not, a normal single cluster environment apply will cause an error as you see above ^

Here is some more log output for more context when it happens

```
DEBU[0329]   vault_unseal_key_name: "" => "vault-jvl-"  app=tarmak module=terraform std=out
DEBU[0329] received rpc vault cluster status             app=tarmak
DEBU[0329] check SSH connection to bastion cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config bastion /bin/true]  app=tarmak destination=vault-1.tarmak.local
DEBU[0329] check SSH connection to bastion cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config bastion /bin/true]  app=tarmak destination=vault-2.tarmak.local
DEBU[0329] check SSH connection to bastion cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config bastion /bin/true]  app=tarmak destination=vault-3.tarmak.local
DEBU[0329] check SSH connection to bastion cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config bastion /bin/true]  app=tarmak destination=vault-3.tarmak.local
DEBU[0329] check SSH connection to bastion cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config bastion /bin/true]  app=tarmak destination=vault-1.tarmak.local
DEBU[0329] check SSH connection to bastion cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config bastion /bin/true]  app=tarmak destination=vault-2.tarmak.local
DEBU[0329] start tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O forward -L127.0.0.1:41061:vault-1.tarmak.local:8200 bastion]  app=tarmak destination=vault-1.tarmak.local
DEBU[0329] start tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O forward -L127.0.0.1:45013:vault-2.tarmak.local:8200 bastion]  app=tarmak destination=vault-2.tarmak.local
DEBU[0329] start tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O forward -L127.0.0.1:33211:vault-3.tarmak.local:8200 bastion]  app=tarmak destination=vault-3.tarmak.local
DEBU[0329] start tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O forward -L127.0.0.1:40709:vault-3.tarmak.local:8200 bastion]  app=tarmak destination=vault-3.tarmak.local
DEBU[0329] start tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O forward -L127.0.0.1:39215:vault-2.tarmak.local:8200 bastion]  app=tarmak destination=vault-2.tarmak.local
DEBU[0329] start tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O forward -L127.0.0.1:35891:vault-1.tarmak.local:8200 bastion]  app=tarmak destination=vault-1.tarmak.local
INFO[0332] setting up init root token, waiting for vault to be unsealed 
INFO[0332] vault still sealed, wait for unsealing       
DEBU[0333] a quorum of vault instances is sealed, retrying  app=tarmak cluster=cluster environment=jvl module=vault
DEBU[0334] stop tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O cancel -L127.0.0.1:39215:vault-2.tarmak.local:8200 bastion]  app=tarmak destination=vault-2.tarmak.local
DEBU[0334] stop tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O cancel -L127.0.0.1:40709:vault-3.tarmak.local:8200 bastion]  app=tarmak destination=vault-3.tarmak.local
DEBU[0334] stop tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O cancel -L127.0.0.1:35891:vault-1.tarmak.local:8200 bastion]  app=tarmak destination=vault-1.tarmak.local
DEBU[0334] check SSH connection to bastion cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config bastion /bin/true]  app=tarmak destination=vault-3.tarmak.local
DEBU[0334] check SSH connection to bastion cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config bastion /bin/true]  app=tarmak destination=vault-1.tarmak.local
DEBU[0334] check SSH connection to bastion cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config bastion /bin/true]  app=tarmak destination=vault-2.tarmak.local
DEBU[0334] start tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O forward -L127.0.0.1:42827:vault-2.tarmak.local:8200 bastion]  app=tarmak destination=vault-2.tarmak.local
DEBU[0334] start tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O forward -L127.0.0.1:43395:vault-3.tarmak.local:8200 bastion]  app=tarmak destination=vault-3.tarmak.local
DEBU[0334] start tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O forward -L127.0.0.1:39795:vault-1.tarmak.local:8200 bastion]  app=tarmak destination=vault-1.tarmak.local
DEBU[0334] active channel position recieved              app=tarmak cluster=cluster environment=jvl module=vault
DEBU[0334] stop tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O cancel -L127.0.0.1:42827:vault-2.tarmak.local:8200 bastion]  app=tarmak destination=vault-2.tarmak.local
DEBU[0334] stop tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O cancel -L127.0.0.1:43395:vault-3.tarmak.local:8200 bastion]  app=tarmak destination=vault-3.tarmak.local
ERRO[0334] vault cluster is not ready: 1 error occurred:

* error listing mounts: Error making API request.

URL: GET https://127.0.0.1:39795/v1/sys/mounts
Code: 403. Errors:

* permission denied  app=tarmak
DEBU[0334] stop tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O cancel -L127.0.0.1:39795:vault-1.tarmak.local:8200 bastion]  app=tarmak destination=vault-1.tarmak.local
INFO[0334] vault successfully initialised                app=tarmak cluster=cluster environment=jvl module=vault
DEBU[0334] stop tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O cancel -L127.0.0.1:33211:vault-3.tarmak.local:8200 bastion]  app=tarmak destination=vault-3.tarmak.local
DEBU[0334] stop tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O cancel -L127.0.0.1:41061:vault-1.tarmak.local:8200 bastion]  app=tarmak destination=vault-1.tarmak.local
DEBU[0334] stop tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O cancel -L127.0.0.1:45013:vault-2.tarmak.local:8200 bastion]  app=tarmak destination=vault-2.tarmak.local
DEBU[0334] check SSH connection to bastion cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config bastion /bin/true]  app=tarmak destination=vault-3.tarmak.local
DEBU[0334] check SSH connection to bastion cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config bastion /bin/true]  app=tarmak destination=vault-2.tarmak.local
DEBU[0334] check SSH connection to bastion cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config bastion /bin/true]  app=tarmak destination=vault-1.tarmak.local
DEBU[0334] start tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O forward -L127.0.0.1:42605:vault-1.tarmak.local:8200 bastion]  app=tarmak destination=vault-1.tarmak.local
DEBU[0334] start tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O forward -L127.0.0.1:43713:vault-2.tarmak.local:8200 bastion]  app=tarmak destination=vault-2.tarmak.local
DEBU[0334] start tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O forward -L127.0.0.1:45717:vault-3.tarmak.local:8200 bastion]  app=tarmak destination=vault-3.tarmak.local
DEBU[0335] active channel position recieved              app=tarmak cluster=cluster environment=jvl module=vault
DEBU[0335] stop tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O cancel -L127.0.0.1:43713:vault-2.tarmak.local:8200 bastion]  app=tarmak destination=vault-2.tarmak.local
DEBU[0335] stop tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O cancel -L127.0.0.1:45717:vault-3.tarmak.local:8200 bastion]  app=tarmak destination=vault-3.tarmak.local
DEBU[0335] No mounts found for: etcd-k8s                 app=tarmak
INFO[0335] Mounted 'etcd-k8s'                            app=tarmak
DEBU[0335] Tuned Mount: etcd-k8s                         app=tarmak
DEBU[0336] No mounts found for: etcd-overlay             app=tarmak
INFO[0336] Mounted 'etcd-overlay'                        app=tarmak
DEBU[0336] Tuned Mount: etcd-overlay                     app=tarmak
DEBU[0337] No mounts found for: k8s                      app=tarmak
INFO[0337] Mounted 'k8s'                                 app=tarmak
DEBU[0337] Tuned Mount: k8s                              app=tarmak
DEBU[0338] No mounts found for: k8s-api-proxy            app=tarmak
INFO[0338] Mounted 'k8s-api-proxy'                       app=tarmak
DEBU[0338] Tuned Mount: k8s-api-proxy                    app=tarmak
DEBU[0339] No secrects mount found for: jvl-cluster/secrets  app=tarmak
INFO[0339] Mounted secrets: 'jvl-cluster/secrets'        app=tarmak
DEBU[0339] module.vault.tarmak_vault_cluster.vault: Still creating... (10s elapsed)  app=tarmak module=terraform std=out
INFO[0343] Key written to secrets 'jvl-cluster/secrets/service-accounts'  app=tarmak
INFO[0343] Key written to secrets 'jvl-cluster/secrets/encryption-config'  app=tarmak
INFO[0345] Policies written for: 'etcd'  'master'  'worker'    app=tarmak
INFO[0345] Init token written for 'etcd' at 'jvl-cluster/secrets/init_token_etcd'  app=tarmak
INFO[0346] Init token written for 'master' at 'jvl-cluster/secrets/init_token_master'  app=tarmak
INFO[0346] Init token written for 'worker' at 'jvl-cluster/secrets/init_token_worker'  app=tarmak
INFO[0347] Init token written for 'all' at 'jvl-cluster/secrets/init_token_all'  app=tarmak
DEBU[0348] stop tunnel cmd=[ssh -F /home/josh/.tarmak/multi/jvl-cluster/ssh_config -O cancel -L127.0.0.1:42605:vault-1.tarmak.local:8200 bastion]  app=tarmak destination=vault-1.tarmak.local
DEBU[0348] module.vault.tarmak_vault_cluster.vault: Creation complete after 19s (ID: 293cde8472d55c1af51125061222b168)  app=tarmak module=terraform std=out
DEBU[0352]                                          app=tarmak module=terraform std=err
DEBU[0352] Error: Error applying plan:  app=tarmak module=terraform std=err
DEBU[0352]                                               app=tarmak module=terraform std=err
DEBU[0352] 1 error occurred:                             app=tarmak module=terraform std=err
DEBU[0352]                                               app=tarmak module=terraform std=err
DEBU[0352] * module.kubernetes.tarmak_vault_cluster.vault: 1 error occurred:  app=tarmak module=terraform std=err
DEBU[0352]                                               app=tarmak module=terraform std=err
DEBU[0352] * tarmak_vault_cluster.vault: call to Tarmak.VaultClusterStatus failed: vault cluster is not ready: 1 error occurred:  app=tarmak module=terraform std=err
DEBU[0352]                                               app=tarmak module=terraform std=err
DEBU[0352] * error listing mounts: Error making API request.  app=tarmak module=terraform std=err
DEBU[0352]                                               app=tarmak module=terraform std=err
DEBU[0352] URL: GET https://127.0.0.1:39795/v1/sys/mounts  app=tarmak module=terraform std=err
DEBU[0352] Code: 403. Errors:                            app=tarmak module=terraform std=err
DEBU[0352]                                               app=tarmak module=terraform std=err
DEBU[0352] * permission denied                           app=tarmak module=terraform std=err
DEBU[0352]                                               app=tarmak module=terraform std=err
DEBU[0352] Terraform does not automatically rollback in the face of errors.  app=tarmak module=terraform std=err
DEBU[0352] Instead, your Terraform state file has been partially updated with  app=tarmak module=terraform std=err
DEBU[0352] any resources that successfully completed. Please address the error  app=tarmak module=terraform std=err
DEBU[0352] above and apply again to incrementally change your infrastructure.  app=tarmak module=terraform std=err
DEBU[0352]                                               app=tarmak module=terraform std=err
DEBU[0352]   
```

It's confusing since the dry run ensure here:
https://github.com/jetstack/tarmak/blob/57530a7c049dd2dd6860c4a6d102a1d182a32580/pkg/terraform/providers/tarmak/rpc/vault_cluster_status.go#L74

will only happen once vault has been initialised however will return a 403. As you can see from the logs, it does actually work after it has errored. Let me know if you need more details

**Comment by simonswine** [comment]
/approve
/lgtm

Thank you both @JoshVanL @MattiasGees

**Pull request merged**
